from typing import Dict, NamedTuple

from .constants import Locations, Researches, Expansions


class RimWorldLocationData(NamedTuple):
    name: str
    category: str
    expansion: str

    def identifier(self) -> str:
        return f"{self.category}: {self.name}"


simple_research_locations: Dict[int, RimWorldLocationData] = {
    11_001: RimWorldLocationData(Researches.PSYCHOIDBREWING, Locations.Categories.RESEARCH, Expansions.CORE),
    11_002: RimWorldLocationData(Researches.TREESOWING, Locations.Categories.RESEARCH, Expansions.CORE),
    11_003: RimWorldLocationData(Researches.BREWING, Locations.Categories.RESEARCH, Expansions.CORE),
    11_004: RimWorldLocationData(Researches.COMPLEXFURNITURE, Locations.Categories.RESEARCH, Expansions.CORE),
    11_005: RimWorldLocationData(Researches.PASSIVECOOLER, Locations.Categories.RESEARCH, Expansions.CORE),
    11_006: RimWorldLocationData(Researches.STONECUTTING, Locations.Categories.RESEARCH, Expansions.CORE),
    11_007: RimWorldLocationData(Researches.COMPLEXCLOTHING, Locations.Categories.RESEARCH, Expansions.CORE),
    11_008: RimWorldLocationData(Researches.DRUGPRODUCTION, Locations.Categories.RESEARCH, Expansions.CORE),
    11_009: RimWorldLocationData(Researches.COCOA, Locations.Categories.RESEARCH, Expansions.CORE),
    11_010: RimWorldLocationData(Researches.DEVILSTRAND, Locations.Categories.RESEARCH, Expansions.CORE),
    11_011: RimWorldLocationData(Researches.CARPETMAKING, Locations.Categories.RESEARCH, Expansions.CORE),
    11_012: RimWorldLocationData(Researches.PEMMICAN, Locations.Categories.RESEARCH, Expansions.CORE),
    11_013: RimWorldLocationData(Researches.SMITHING, Locations.Categories.RESEARCH, Expansions.CORE),
    11_014: RimWorldLocationData(Researches.RECURVEBOW, Locations.Categories.RESEARCH, Expansions.CORE),
    11_015: RimWorldLocationData(Researches.PSYCHITEREFINING, Locations.Categories.RESEARCH, Expansions.CORE),
    11_016: RimWorldLocationData(Researches.WAKEUPPRODUCTION, Locations.Categories.RESEARCH, Expansions.CORE),
    11_017: RimWorldLocationData(Researches.GOJUICEPRODUCTION, Locations.Categories.RESEARCH, Expansions.CORE),
    11_018: RimWorldLocationData(Researches.PENOXYCYLINEPRODUCTION, Locations.Categories.RESEARCH, Expansions.CORE),
    11_019: RimWorldLocationData(Researches.LONGBLADES, Locations.Categories.RESEARCH, Expansions.CORE),
    11_020: RimWorldLocationData(Researches.PLATEARMOR, Locations.Categories.RESEARCH, Expansions.CORE),
    11_021: RimWorldLocationData(Researches.GREATBOW, Locations.Categories.RESEARCH, Expansions.CORE),
    11_022: RimWorldLocationData(Researches.ELECTRICITY, Locations.Categories.RESEARCH, Expansions.CORE),
    11_023: RimWorldLocationData(Researches.BATTERIES, Locations.Categories.RESEARCH, Expansions.CORE),
    11_024: RimWorldLocationData(Researches.BIOFUELREFINING, Locations.Categories.RESEARCH, Expansions.CORE),
    11_025: RimWorldLocationData(Researches.WATERMILLGENERATOR, Locations.Categories.RESEARCH, Expansions.CORE),
    11_026: RimWorldLocationData(Researches.NUTRIENTPASTE, Locations.Categories.RESEARCH, Expansions.CORE),
    11_027: RimWorldLocationData(Researches.SOLARPANELS, Locations.Categories.RESEARCH, Expansions.CORE),
    11_028: RimWorldLocationData(Researches.AIRCONDITIONING, Locations.Categories.RESEARCH, Expansions.CORE),
    11_029: RimWorldLocationData(Researches.AUTODOORS, Locations.Categories.RESEARCH, Expansions.CORE),
    11_030: RimWorldLocationData(Researches.HYDROPONICS, Locations.Categories.RESEARCH, Expansions.CORE),
    11_031: RimWorldLocationData(Researches.TUBETELEVISION, Locations.Categories.RESEARCH, Expansions.CORE),
    11_032: RimWorldLocationData(Researches.PACKAGEDSURVIVALMEAL, Locations.Categories.RESEARCH, Expansions.CORE),
    11_033: RimWorldLocationData(Researches.FIREFOAM, Locations.Categories.RESEARCH, Expansions.CORE),
    11_034: RimWorldLocationData(Researches.IEDS, Locations.Categories.RESEARCH, Expansions.CORE),
    11_035: RimWorldLocationData(Researches.GEOTHERMALPOWER, Locations.Categories.RESEARCH, Expansions.CORE),
    11_036: RimWorldLocationData(Researches.STERILEMATERIALS, Locations.Categories.RESEARCH, Expansions.CORE),
    11_037: RimWorldLocationData(Researches.COLOREDLIGHTS, Locations.Categories.RESEARCH, Expansions.CORE),
    11_038: RimWorldLocationData(Researches.MACHINING, Locations.Categories.RESEARCH, Expansions.CORE),
    11_039: RimWorldLocationData(Researches.SMOKEPOPBELT, Locations.Categories.RESEARCH, Expansions.CORE),
    11_040: RimWorldLocationData(Researches.PROSTHETICS, Locations.Categories.RESEARCH, Expansions.CORE),
    11_041: RimWorldLocationData(Researches.GUNSMITHING, Locations.Categories.RESEARCH, Expansions.CORE),
    11_042: RimWorldLocationData(Researches.FLAKARMOR, Locations.Categories.RESEARCH, Expansions.CORE),
    11_043: RimWorldLocationData(Researches.MORTARS, Locations.Categories.RESEARCH, Expansions.CORE),
    11_044: RimWorldLocationData(Researches.BLOWBACKOPERATION, Locations.Categories.RESEARCH, Expansions.CORE),
    11_045: RimWorldLocationData(Researches.GASOPERATION, Locations.Categories.RESEARCH, Expansions.CORE),
    11_046: RimWorldLocationData(Researches.GUNTURRETS, Locations.Categories.RESEARCH, Expansions.CORE),
    11_047: RimWorldLocationData(Researches.FOAMTURRET, Locations.Categories.RESEARCH, Expansions.CORE),
    11_048: RimWorldLocationData(Researches.MICROELECTRONICSBASICS, Locations.Categories.RESEARCH, Expansions.CORE),
    11_049: RimWorldLocationData(Researches.BASICMECHTECH, Locations.Categories.RESEARCH, Expansions.BIOTECH),
    11_050: RimWorldLocationData(Researches.STANDARDMECHTECH, Locations.Categories.RESEARCH, Expansions.BIOTECH),
    11_051: RimWorldLocationData(Researches.WASTEPACKATOMIZER, Locations.Categories.RESEARCH, Expansions.BIOTECH),
    11_052: RimWorldLocationData(Researches.TOXIFIERGENERATOR, Locations.Categories.RESEARCH, Expansions.BIOTECH),
    11_053: RimWorldLocationData(Researches.XENOGERMINATION, Locations.Categories.RESEARCH, Expansions.BIOTECH),
    11_054: RimWorldLocationData(Researches.DEATHREST, Locations.Categories.RESEARCH, Expansions.BIOTECH),
    11_055: RimWorldLocationData(Researches.FERTILITYPROCEDURES, Locations.Categories.RESEARCH, Expansions.BIOTECH),
    11_056: RimWorldLocationData(Researches.TOXGAS, Locations.Categories.RESEARCH, Expansions.BIOTECH),
    11_057: RimWorldLocationData(Researches.TOXFILTRATION, Locations.Categories.RESEARCH, Expansions.BIOTECH),
    11_058: RimWorldLocationData(Researches.NOBLEAPPAREL, Locations.Categories.RESEARCH, Expansions.ROYALTY),
    11_059: RimWorldLocationData(Researches.ROYALAPPAREL, Locations.Categories.RESEARCH, Expansions.ROYALTY),
    11_060: RimWorldLocationData(Researches.COMPACTWEAPONRY, Locations.Categories.RESEARCH, Expansions.ROYALTY),
    11_061: RimWorldLocationData(Researches.HARP, Locations.Categories.RESEARCH, Expansions.ROYALTY),
    11_062: RimWorldLocationData(Researches.HARPSICHORD, Locations.Categories.RESEARCH, Expansions.ROYALTY),
    11_063: RimWorldLocationData(Researches.PIANO, Locations.Categories.RESEARCH, Expansions.ROYALTY),
}

hitech_research_locations: Dict[int, RimWorldLocationData] = {
    11_064: RimWorldLocationData(Researches.FLATSCREENTELEVISION, Locations.Categories.RESEARCH, Expansions.CORE),
    11_065: RimWorldLocationData(Researches.MOISTUREPUMP, Locations.Categories.RESEARCH, Expansions.CORE),
    11_066: RimWorldLocationData(Researches.HOSPITALBED, Locations.Categories.RESEARCH, Expansions.CORE),
    11_067: RimWorldLocationData(Researches.DEEPDRILLING, Locations.Categories.RESEARCH, Expansions.CORE),
    11_068: RimWorldLocationData(Researches.GROUNDPENETRATINGSCANNER, Locations.Categories.RESEARCH, Expansions.CORE),
    11_069: RimWorldLocationData(Researches.TRANSPORTPOD, Locations.Categories.RESEARCH, Expansions.CORE),
    11_070: RimWorldLocationData(Researches.MEDICINEPRODUCTION, Locations.Categories.RESEARCH, Expansions.CORE),
    11_071: RimWorldLocationData(Researches.LONGRANGEMINERALSCANNER, Locations.Categories.RESEARCH, Expansions.CORE),
    11_072: RimWorldLocationData(Researches.SHIELDBELT, Locations.Categories.RESEARCH, Expansions.CORE),
    11_073: RimWorldLocationData(Researches.PRECISIONRIFLING, Locations.Categories.RESEARCH, Expansions.CORE),
    11_074: RimWorldLocationData(Researches.HEAVYTURRETS, Locations.Categories.RESEARCH, Expansions.CORE),
    11_075: RimWorldLocationData(Researches.MULTIBARRELWEAPONS, Locations.Categories.RESEARCH, Expansions.CORE),
    11_076: RimWorldLocationData(Researches.MULTIANALYZER, Locations.Categories.RESEARCH, Expansions.CORE),
    11_077: RimWorldLocationData(Researches.GENEPROCESSOR, Locations.Categories.RESEARCH, Expansions.BIOTECH),
    11_078: RimWorldLocationData(Researches.ARCHOGENETICS, Locations.Categories.RESEARCH, Expansions.BIOTECH),
    11_079: RimWorldLocationData(Researches.GROWTHVATS, Locations.Categories.RESEARCH, Expansions.BIOTECH),
    11_080: RimWorldLocationData(Researches.BIOSCULPTING, Locations.Categories.RESEARCH, Expansions.IDEOLOGY),
    11_081: RimWorldLocationData(Researches.BIOREGENERATION, Locations.Categories.RESEARCH, Expansions.IDEOLOGY),
    11_082: RimWorldLocationData(Researches.NEURALSUPERCHARGER, Locations.Categories.RESEARCH, Expansions.IDEOLOGY),
    11_083: RimWorldLocationData(Researches.JUMPPACK, Locations.Categories.RESEARCH, Expansions.ROYALTY),
    11_084: RimWorldLocationData(Researches.GUNLINK, Locations.Categories.RESEARCH, Expansions.ROYALTY),
    11_085: RimWorldLocationData(Researches.BRAINWIRING, Locations.Categories.RESEARCH, Expansions.ROYALTY),
    11_086: RimWorldLocationData(Researches.SPECIALIZEDLIMBS, Locations.Categories.RESEARCH, Expansions.ROYALTY),
    11_087: RimWorldLocationData(Researches.VENOMSYNTHESIS, Locations.Categories.RESEARCH, Expansions.ROYALTY),
}

multi_analyzer_research_locations: Dict[int, RimWorldLocationData] = {
    11_088: RimWorldLocationData(Researches.VITALSMONITOR, Locations.Categories.RESEARCH, Expansions.CORE),
    11_089: RimWorldLocationData(Researches.FABRICATION, Locations.Categories.RESEARCH, Expansions.CORE),
    11_090: RimWorldLocationData(Researches.ADVANCEDFABRICATION, Locations.Categories.RESEARCH, Expansions.CORE),
    11_091: RimWorldLocationData(Researches.CRYPTOSLEEP, Locations.Categories.RESEARCH, Expansions.CORE),
    11_092: RimWorldLocationData(Researches.RECONARMOR, Locations.Categories.RESEARCH, Expansions.CORE),
    11_093: RimWorldLocationData(Researches.POWEREDARMOR, Locations.Categories.RESEARCH, Expansions.CORE),
    11_094: RimWorldLocationData(Researches.CHARGEDSHOT, Locations.Categories.RESEARCH, Expansions.CORE),
    11_095: RimWorldLocationData(Researches.BIONICS, Locations.Categories.RESEARCH, Expansions.CORE),
    11_096: RimWorldLocationData(Researches.SNIPERTURRET, Locations.Categories.RESEARCH, Expansions.CORE),
    11_097: RimWorldLocationData(Researches.ROCKETSWARMLAUNCHER, Locations.Categories.RESEARCH, Expansions.CORE),
    11_098: RimWorldLocationData(Researches.SHIPBASICS, Locations.Categories.RESEARCH, Expansions.CORE),
    11_099: RimWorldLocationData(Researches.SHIPCRYPTOSLEEP, Locations.Categories.RESEARCH, Expansions.CORE),
    11_100: RimWorldLocationData(Researches.SHIPREACTOR, Locations.Categories.RESEARCH, Expansions.CORE),
    11_101: RimWorldLocationData(Researches.SHIPENGINE, Locations.Categories.RESEARCH, Expansions.CORE),
    11_102: RimWorldLocationData(Researches.SHIPCOMPUTERCORE, Locations.Categories.RESEARCH, Expansions.CORE),
    11_103: RimWorldLocationData(Researches.SHIPSENSORCLUSTER, Locations.Categories.RESEARCH, Expansions.CORE),
    11_104: RimWorldLocationData(Researches.HIGHMECHTECH, Locations.Categories.RESEARCH, Expansions.BIOTECH),
    11_105: RimWorldLocationData(Researches.ULTRAMECHTECH, Locations.Categories.RESEARCH, Expansions.BIOTECH),
    11_106: RimWorldLocationData(Researches.CATAPHRACTARMOR, Locations.Categories.RESEARCH, Expansions.ROYALTY),
    11_107: RimWorldLocationData(Researches.ARTIFICIALMETABOLISM, Locations.Categories.RESEARCH, Expansions.ROYALTY),
    11_108: RimWorldLocationData(Researches.NEURALCOMPUTATION, Locations.Categories.RESEARCH, Expansions.ROYALTY),
    11_109: RimWorldLocationData(Researches.SKINHARDENING, Locations.Categories.RESEARCH, Expansions.ROYALTY),
    11_110: RimWorldLocationData(Researches.HEALINGFACTORS, Locations.Categories.RESEARCH, Expansions.ROYALTY),
    11_111: RimWorldLocationData(Researches.FLESHSHAPING, Locations.Categories.RESEARCH, Expansions.ROYALTY),
    11_112: RimWorldLocationData(Researches.MOLECULARANALYSIS, Locations.Categories.RESEARCH, Expansions.ROYALTY),
    11_113: RimWorldLocationData(Researches.CIRCADIANINFLUENCE, Locations.Categories.RESEARCH, Expansions.ROYALTY),
}

all_locations: Dict[int, RimWorldLocationData] = {**simple_research_locations, **hitech_research_locations,
                                                  **multi_analyzer_research_locations}

all_locations_name_to_id = {value.identifier(): key for key, value in all_locations.items()}
